const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE';
const REGiSTER_REQUEST = 'REGiSTER_REQUEST';
const REGiSTER_REQUEST_SUCCESS = 'REGiSTER_REQUEST_SUCCESS';
const REGiSTER_REQUEST_FAILURE = 'REGiSTER_REQUEST_FAILURE';
const FORGOT_REQUEST_SUCCESS = 'FORGOT_REQUEST_SUCCESS';
const CONFIRM_REQUEST_SUCCESS = 'CONFIRM_REQUEST_SUCCESS';
const RESET_REQUEST_SUCCESS = 'RESET_REQUEST_SUCCESS';
const EXIT = 'EXIT';

export {
  LOGIN_REQUEST,
  LOGIN_REQUEST_SUCCESS,
  LOGIN_REQUEST_FAILURE,
  REGiSTER_REQUEST,
  REGiSTER_REQUEST_SUCCESS,
  REGiSTER_REQUEST_FAILURE,
  FORGOT_REQUEST_SUCCESS,
  CONFIRM_REQUEST_SUCCESS,
  RESET_REQUEST_SUCCESS,
  EXIT
}