import React from 'react';
import LocalizedStrings from 'react-native-localization';
import {Text} from "native-base";


const strings = new LocalizedStrings({
    "en": {
        SignUp: "Sign Up",
        LogIn: 'Log In',
        Email: 'Email',
        Password: 'Password',
        PasswordConfirm: " Password Confirm ",
        AlreadyHaveAnAccount: "Already have an account?",
        ForgotPassword: 'Forgot password?',
        FirstTimeHere: 'First time here?',
        UserName: "Username",
        EmailIsNotCorrect: 'Email is not correct',
        PasswordLengthShould: "Password length should be more than 6 sign",
        PasswordDoesNotMatch: "Password does not match",
        AllFieldsShouldBeFilled: "All fields should be filled",
        Home_N: 'Home',
        StartVideo: 'Start Video',
        MyProfile: 'My Profile',
        Messages: 'Messages',
        MyVideos: 'My Videos',
        Notifications: 'Notifications',
        LegalDetails: 'Legal Details',
        Tutorial: 'Tutorial',
        Logout: 'Logout',
        StartRecord: 'Start record',
        ProfilePage: 'Profile Page',
        MessagesPage: 'Messages Page',
        VideosPage: 'Videos Page',
        NotificationPage: 'Notification page',
        LegalDetailsPage: 'Legal Details page',
        TutorialPage: 'Tutorial page',
    },
    "fr": {
        SignUp: "S'inscrire",
        LogIn: "S'identifier",
        Email: 'Email',
        Password: 'Mot de passe',
        PasswordConfirm: "Confirmer le mot de passe ",
        AlreadyHaveAnAccount: "Vous avez déjà un compte?",
        ForgotPassword: 'Mot de passe oublié?',
        FirstTimeHere: 'Première fois ici?',
        UserName: "Nom d'utilisateur",
        EmailIsNotCorrect: "L'email n'est pas correct",
        PasswordLengthShould: "La longueur du mot de passe doit être supérieure à 6 signes",
        PasswordDoesNotMatch: "Le mot de passe ne correspond pas",
        AllFieldsShouldBeFilled: "Tous les champs doivent être remplis",
        Home_N: 'Accueil',
        StartVideo: 'Démarrer la vidéo',
        MyProfile: 'Mon profil',
        Messages: 'Messages',
        MyVideos: 'Mes vidéos',
        Notifications: 'Les notifications',
        LegalDetails: 'Détails légaux',
        Tutorial: 'Didacticiel',
        Logout: 'Connectez - Out',
        StartRecord: 'Enregistrement de départ',
        ProfilePage: 'Page de profil',
        MessagesPage: 'Messages',
        VideosPage: 'Page de vidéos',
        NotificationPage: 'Page de notification',
        LegalDetailsPage: 'Page de détails juridiques',
        TutorialPage: 'Page tutoriel',
    }
});
export default strings;